In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('tb_boutique.csv')
df.head()

,longitude,latitude,departement,ville,adresse,code_postal,boutique_id,Responsable
0,-1.51815,43.49507,Pyrénées-Atlantiques,Anglet,Avenue Belle Marion,64600,1,1
1,-1.42988,46.66976,Vendée,La Roche-sur-Yon,15 Rue Georges Clémenceau,85000,2,1
2,-1.43024,46.69141,Vendée,La Roche-sur-Yon,CC Les Flaneries,85000,3,1
3,-1.54907,47.16152,Loire-Atlantique,Rezé,"10 rond-point Corbinerie ,CC Océane",44400,4,1
4,-1.46916,47.18722,Loire-Atlantique,Basse-Goulaine,CC Leclerc Pôle Sud,44115,5,1

In [20]:
df['nom_boutique'] = "Free shop " + df['code_postal'].astype(str).str[:2] + " _ "+df['boutique_id'].astype(str)

In [21]:
df['nom_boutique']

0        Free shop 64 _ 1
1        Free shop 85 _ 2
2        Free shop 85 _ 3
3        Free shop 44 _ 4
4        Free shop 44 _ 5
              ...
221    Free shop 35 _ 222
222    Free shop 35 _ 223
223    Free shop 35 _ 224
224    Free shop 35 _ 225
225    Free shop 56 _ 226
Name: nom_boutique, Length: 226, dtype: object

In [22]:
df.head()

,longitude,latitude,departement,ville,adresse,code_postal,boutique_id,Responsable,nom_boutique
0,-1.51815,43.49507,Pyrénées-Atlantiques,Anglet,Avenue Belle Marion,64600,1,1,Free shop 64 _ 1
1,-1.42988,46.66976,Vendée,La Roche-sur-Yon,15 Rue Georges Clémenceau,85000,2,1,Free shop 85 _ 2
2,-1.43024,46.69141,Vendée,La Roche-sur-Yon,CC Les Flaneries,85000,3,1,Free shop 85 _ 3
3,-1.54907,47.16152,Loire-Atlantique,Rezé,"10 rond-point Corbinerie ,CC Océane",44400,4,1,Free shop 44 _ 4
4,-1.46916,47.18722,Loire-Atlantique,Basse-Goulaine,CC Leclerc Pôle Sud,44115,5,1,Free shop 44 _ 5

In [23]:
# convertir la colonne 'Responsable' en 'responsable'
df.rename(columns={'Responsable': 'responsable'}, inplace=True)

In [24]:
df_copy = df [['nom_boutique', 'adresse', 'ville','code_postal', 'departement' ,'latitude', 'longitude', 'responsable']].copy()

In [26]:
df_copy.head(20)

,nom_boutique,adresse,ville,code_postal,departement,latitude,longitude,responsable
0,Free shop 64 _ 1,Avenue Belle Marion,Anglet,64600,Pyrénées-Atlantiques,43.49507,-1.51815,1
1,Free shop 85 _ 2,15 Rue Georges Clémenceau,La Roche-sur-Yon,85000,Vendée,46.66976,-1.42988,1
2,Free shop 85 _ 3,CC Les Flaneries,La Roche-sur-Yon,85000,Vendée,46.69141,-1.43024,1
3,Free shop 44 _ 4,"10 rond-point Corbinerie ,CC Océane",Rezé,44400,Loire-Atlantique,47.16152,-1.54907,1
4,Free shop 44 _ 5,CC Leclerc Pôle Sud,Basse-Goulaine,44115,Loire-Atlantique,47.18722,-1.46916,1
5,Free shop 44 _ 6,CC Auchan,Saint-Sébastien-sur-Loire,44230,Loire-Atlantique,47.19164,-1.49383,1
6,Free shop 44 _ 7,"CC Leclerc Atout Sud ,1 Rue Ordronneau",Rezé,44400,Loire-Atlantique,47.19424,-1.57205,1
7,Free shop 44 _ 8,"6 Rue du Dr Zamenhoff ,CC Beaulieu",Nantes,44202,Loire-Atlantique,47.20456,-1.53510,1
8,Free shop 44 _ 9,14 Rue de la Contrescarpe,Nantes,44003,Loire-Atlantique,47.21496,-1.55925,1
9,Free shop 22 _ 10,CC Guingamp,Guingamp,22200,Côtes-d'Armor,48.56226,-3.16566,1
10,Free shop 44 _ 11,"28 Rue de la Marne ,Quartier Decré",Nantes,44000,Loire-Atlantique,47.21563,-1.55471,1
11,Free shop 44 _ 12,CC Atlantis,Saint-Herblain,44800,Loire-Atlantique,47.22492,-1.63044,1
12,Free shop 44 _ 13,"14 Route de Paris ,CC Paridis",Nantes,44300,Loire-Atlantique,47.25076,-1.51842,1
13,Free shop 44 _ 14,CC Géant Océanis,Saint-Nazaire,44600,Loire-Atlantique,47.25845,-2.26452,1
14,Free shop 44 _ 15,2 Avenue de la République,Saint-Nazaire,44600,Loire-Atlantique,47.27441,-2.21331,1
15,Free shop 44 _ 16,128 Avenue du Général de Gaulle,La Baule-Escoublac,44500,Loire-Atlantique,47.28597,-2.39138,1
16,Free shop 44 _ 17,CC Auchan,Trignac,44570,Loire-Atlantique,47.30136,-2.20884,1
17,Free shop 44 _ 18,Place du Marhallé,Guérande,44350,Loire-Atlantique,47.32693,-2.42696,1
18,Free shop 35 _ 19,50 Grande-Rue,Redon,35600,Ille-et-Vilaine,47.64874,-2.08496,1
19,Free shop 56 _ 20,15 Place de la République,Vannes,56000,Morbihan,47.65561,-2.76058,3

In [27]:
df_copy.to_csv('tb_boutique_final.csv', index=False)

In [8]:
df_prod = pd.read_csv('tb_produit_output.csv')
df_prod.dtypes

id_produit      int64
nom_produit    object
prix            int64
couleur        object
capacite        int64
ram             int64
image          object
modele          int64
boutique_id     int64
dtype: object

In [9]:
df_prod_copy = df_prod[['boutique_id', 'nom_produit', 'prix', 'couleur', 'capacite', 'ram', 'modele', 'image']].copy()
df_prod_copy.head()

,boutique_id,nom_produit,prix,couleur,capacite,ram,modele,image
0,57,Poco C3 64 C3 64,8999,Black,64,4,30,https://i.ebayimg.com/00/s/MTUwMFg3MDY%3D/z/jZ...
1,58,Poco M3 64 M3 64,10999,Blue,64,4,100,https://m.media-amazon.com/images/I/61MYP5oYCx...
2,59,Poco M2 Reloaded 64 M2 Reloaded 64,9999,Blue,64,4,98,https://i.ebayimg.com/images/g/EGUAAOSwYV1lhxl...
3,60,Poco C3 32 C3 32,7999,Blue,32,3,29,https://i.ebayimg.com/00/s/MTUwMFg3MDY%3D/z/jZ...
4,61,Poco M3 64 M3 64,11999,Black,64,6,100,https://m.media-amazon.com/images/I/61MYP5oYCx...

In [10]:
df_prod_copy.to_csv('tb_produit_output_final.csv', index=False)